<?php
include_once('Views/template/header.php');
include_once('Models/DeliveryPoint.php');
include_once('Models/DeliveryUser.php');
include_once('Models/DeliveryStatus.php');



$getParcelModel = new DeliveryPoint();
$parcel = $getParcelModel->get($_GET['id']);

$dataModel = new DeliveryUser();
$users = $dataModel->getDeliverers();

$statusModel = new DeliveryStatus();
$statusList  = $statusModel->getAllStatusList();


?>
<div class="container mb-5 pb-2">
    <div class="p-5  border border-secondary mt-5" style="background-color: #fffe;">
        <h4 class="text-center">Parcel Description</h4>
        <hr>
        <form method="post" name="update_form" action="UpdateController.php" enctype="multipart/form-data">
            <div class="form-group">
                <label>Receiver Name</label><input readonly type="text" name="name" value="<?= $parcel['name'] ?>" class="form-control" require>
            </div>
            <div class="form-group">
                <label>Address Line 1</label><input readonly type="text" name="address_1" value="<?= $parcel['address_1'] ?>" class="form-control" require>
            </div>
            <div class="form-group">
                <label>Address Line 2</label><input readonly type="text" name="address_2" value="<?= $parcel['address_2'] ?>" class="form-control" require>
            </div>

            <div class="form-group">
                <label>Postcode</label><input readonly type="text" name="postcode" value="<?= $parcel['postcode'] ?>" class="form-control">
            </div>

            <div class="form-group">
                <label>Latitude</label><input readonly type="text" name="lat" value="<?= $parcel['lat'] ?>" class="form-control" require>
            </div>
            <div class="mt-2">
                <label>Longitude</label><input readonly type="text" name="lng" value="<?= $parcel['lng'] ?>" class="form-control" require>
            </div>
            <div class="form-group">
                <label>Status</label>
                <?php
                while ($st = $statusList->fetch()) {
                    if($parcel['status'] == $st['id']) {
                        ?>
                        <input readonly type="text" name="lng" value="<?= $st['status_text'] ?>" class="form-control" require>
                        <?php
                    }  
                }
                ?>
            </div>
            <div class="form-group">
                <label>Deliverer</label>
                    <?php
                    while ($user = $users->fetch()) {
                        if($parcel['deliverer'] == $user['userid']) {
                            ?>
                            <input readonly type="text" name="lng" value="<?= $user['username']   ?>" class="form-control" require>
                            <?php
                        } 
                    }
                    ?>
            </div>

    </div><br>
    <br>
    </form>
    <br>
</div>
<br>
</div>

<?php include_once('Views/template/footer.php'); ?>