<?php
include_once('Views/template/header.php');
include_once('Models/DeliveryUser.php');
include_once('Models/DeliveryStatus.php');


$dataModel = new DeliveryUser();
$users = $dataModel->getDeliverers();

$statusModel = new DeliveryStatus();
$statusList  = $statusModel->getAllStatusList();


?>

<div class="container mb-5 pb-3" >
    <div class="p-5  border border-secondary" style="background-color: #fffe;">
        <h4 class="text-center">CREATE PARCEL</h4>
        <hr>
        <form name="create_form" method="post" action="CreateController.php" enctype="multipart/form-data">
            <div class="mt-2">
                <label>Recipient Name</label><input type="text" name="name" class="form-control" require>
            </div>
            <div class="mt-2">
                <label>Address 1</label><input type="text" name="address_1" class="form-control" require>
            </div>
            <div class="mt-2">
                <label>Address 2</label><input type="text" name="address_2" class="form-control" >
            </div>

            <div class="mt-2">
                <label>Postcode</label><input type="text" name="postcode" class="form-control" require>
            </div>

            <div class="mt-2">
                <label>Latitude</label><input type="text" name="lat" class="form-control" require>
            </div>
            <div class="mt-2">
                <label>Longitude</label><input type="text" name="lng" class="form-control" require>
            </div>

            <div class="mt-2">
                <label>Image</label><input type="file" class="form-control" name="image" >
            </div>
            <div class="mt-2">
                <label>Parcel Status</label>
                <select name="status" class="form-control" >
                    <?php
                    while ($st = $statusList->fetch()) {
                    ?>
                        <option value="<?= $st['id'] ?>"><?= $st['status_text'] ?></option>
                    <?php
                    }

                    ?>
                </select>
            </div>

            <div class="mt-2">
                <label>Deliverer</label>
                <select name="deliverer"  class="form-control">
                    <?php
                    while ($user = $users->fetch()) {
                    ?>
                        <option value="<?= $user['userid'] ?>"><?= $user['username'] ?></option>
                    <?php
                    }

                    ?>

                </select>
            </div>
            <input  name="store" hidden />
            <div class="mt-2">
                <button name="" type="submit" class="btn btn-primary">Create Record</button>
            </div>
        </form>
    </div> <br><br>
</div>

<?php include_once('Views/template/footer.php'); ?>